stages:
  - deploy

variables:
  BUILD_PATH: "./build/*"
  DEPLOY_PATH: "/srv/cv-graphql"

deploy:
  tags:
    - deployServer
    - unix
  script:
    - "npm install"
    - "npm run build"
    - "rsync -rvL --progress --delete $BUILD_PATH $DEPLOY_PATH"
    - "rsync -rvL --progress --delete ./node_modules $DEPLOY_PATH"
    - "forever restart curriculum-vitae"
  stage: deploy
  environment: Stage
  allow_failure: false
  only:
    - master@david.frtala/curriculum-vitae